# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# env settings
exclude: [vendor]

# Site settings
title: ç‡»è£½ä¼š
description: > # this means to ignore newlines until "baseurl:"
  ã‚‚ãã‚‚ãã™ã‚‹ã‚„ã¤ ğŸš¬
url: "https://knsei.github.io" # the base hostname & protocol for your site
github_username:  knsei

# Build settings
markdown: kramdown
